# Generated by Django 4.2 on 2023-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherforecast_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecast',
            name='wtime',
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='detailing',
            field=models.CharField(choices=[('C', 'Current'), ('M', 'Minutely'), ('H', 'Hourly'), ('D', 'Daily')], max_length=1),
        ),
    ]
